# Generated by Django 3.0.5 on 2020-07-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='content',
            field=models.TextField(default='meet', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default='dixit', max_length=50),
            preserve_default=False,
        ),
    ]
