# Generated by Django 3.0.5 on 2020-07-12 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_auto_20200712_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
